#!/usr/bin/env python
# encoding: utf-8

MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = 'root'
MYSQL_DATABASE_DB = 'cyberminer'
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 8889
MYSQL_DATABASE_PORT2 = 3306
