#!/usr/bin/env python
# encoding: utf-8

MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = 'qq5201314'
MYSQL_DATABASE_DB = 'cyberminer'
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT2 = 8889
MYSQL_DATABASE_PORT = 3306

OUT_OF_DATE_URL_CLEAN_INTERVAL = 3600
